dashboard/urls.py
from django.urls import path, include
from users.forms import CustomUserUpdateForm
from . import views

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('exam/', views.ExamCreateView.as_view(), name="dashboard-exam"),

    path('jadwal/pendaftaran/', views.RegisterSchedule.as_view(), name="schedule"),
    path('jadwal/pendaftaran/create/', views.RegisterScheduleCreateView.as_view(), name="schedule-create"),
    path('jadwal/pendaftaran/delete/<int:pk>/', views.RegisterSchduleDeleteView.as_view(), name="schedule-delete"),
    path('jadwal/pendaftaran/update/<int:pk>/', views.RegisterSchduleUpdateView.as_view(), name="schedule-update"),

    path('siswa/<int:pk>/', views.ProfileDetailView.as_view(), name="detail-student"),
    path('siswa/delete/<int:pk>/', views.ProfileDeleteView.as_view(), name="delete-student"),
    path('ayah/<int:pk>/', views.FatherProfileDetailView.as_view(), name="detail-student-father"),
    path('ibu/<int:pk>/', views.MotherProfileDetailView.as_view(), name="detail-student-mother"),
    path('wali/<int:pk>/', views.GuardianProfileDetailView.as_view(), name="detail-student-guardian"),
    path('jurusan/<int:pk>/', views.MajorProfileDetailView.as_view(), name="detail-student-major"),
    path('berkas/<int:pk>/', views.FilesProfileDetailView.as_view(), name="detail-student-files"),
    path('score/<int:pk>/', views.ScoreListView.as_view(), name="detail-student-score"),
    path('status/<int:pk>/', views.StatusStudentDetailView.as_view(), name="detail-student-status"),
    path('score/<int:pk_user>/<int:pk>/delete/', views.ScoreDeleteView.as_view(), name="detail-student-score-delete"),

    path('users/<int:pk>/', views.UpdateUser.as_view(), name="change-student-name"),
    path('export/', views.export_excel, name="export-student"),
]

exam/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.ExamView.as_view(), name="exam-list"),
    # Exam Path
    path('<int:pk>/', views.ExamViewDetail.as_view(), name="exam-detail"),
    path('<int:pk>/update/', views.ExamUpdateView.as_view(), name="exam-update"),
    path('<int:pk>/delete/', views.ExamDeleteView.as_view(), name="exam-delete"),
    path('<int:pk>/enroll/', views.ExamEnrollView.as_view(), name="exam-enroll"),
    path('<int:pk_exam>/timer/', views.ExamTimerView.as_view(), name="exam-timer"),
    path('<int:pk_exam>/times/up/', views.ExamTimesUpView.as_view(), name="exam-times-up"),
    # Question Path
    path('<int:pk>/question/add/', views.AddQuestion.as_view(), name="question-add"),
    path('<int:pk_exam>/taken/', views.TakeExamView.as_view(), name="taken-question"),
    path('<int:pk_exam>/taken/submit/', views.SubmitAnswer.as_view(), name="submit-question"),
    path('<int:pk_exam>/taken/<int:pk>/', views.RetriveAnswer.as_view(), name="question-answer"),
    path('<int:pk_exam>/question/<int:pk>/delete/', views.QuestionDeleteView.as_view(), name="question-delete"),
    path('<int:pk_exam>/question/<int:pk>/update/', views.QuestionUpdateView.as_view(), name="question-update"),
    path('answer/<int:pk>/', views.AnswerView.as_view(), name="answer-list"),
]

ppdb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from users.forms import CustomAuthenticationForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('primaseru.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('exam/', include('exam.urls')),

    path('login/', auth_views.LoginView.as_view(template_name='users/login.html',
                                                authentication_form=CustomAuthenticationForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models
from django.utils import timezone

from users.models import CustomUser
from primaseru import choices


class StudentStatus(models.Model):
    student = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    accepted = models.BooleanField('Diterima', db_index=True, null=True)
    major = models.CharField('Diterima dijurusan', choices=choices.MAJOR, max_length=4, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.student} Status'

primaseru/models.py
from datetime import date

from django.db import models
from django.utils import timezone

from PIL import Image

from users.models import CustomUser
from . import choices


def user_directory_path(instance, filename):
    return f'berkas_{instance.student.id}_{instance.student.full_name}/{filename}'

class StudentFile(models.Model):
    student = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    verified = models.BooleanField(default=False, db_index=True)
    msg = models.CharField("Pesan", max_length=120, null=True, blank=True)
    ra_sem_1 = models.FileField('Rapor Semester 1', upload_to=user_directory_path, null=True, blank=True)
    ra_sem_2 = models.FileField('Rapor Semester 2', upload_to=user_directory_path, null=True, blank=True)
    ra_sem_3 = models.FileField('Rapor Semester 3', upload_to=user_directory_path, null=True, blank=True)
    ra_sem_4 = models.FileField('Rapor Semester 4', upload_to=user_directory_path, null=True, blank=True)
    ra_sem_5 = models.FileField('Rapor Semester 5', upload_to=user_directory_path, null=True, blank=True)
    color_blind_cert = models.FileField('Semester Keterangan Tidak Buta Warna', upload_to=user_directory_path, null=True, blank=True)
    healty_cert = models.FileField('Surat Keterangan Sehat', upload_to=user_directory_path, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'Raport {self.student}'

class PhotoProfile(models.Model):
    student = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    image = models.ImageField('Photo', default='default_photo.png', upload_to='profile_pics')

    def __str__(self):
        return f'Photo {self.student}'

    def save(self, *args, **kwargs):
        super(PhotoProfile, self).save(*args, **kwargs)
        img = Image.open(self.image.path)

        if img.height > 400 or img.width > 400:
            output_size = (400,400)
            img.thumbnail(output_size)
            img.save(self.image.path)


class StudentProfile(models.Model):
    verified = models.BooleanField(default=False, db_index=True)
    # Personal Information
    student = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    no_regis = models.PositiveIntegerField('No. Pendaftaran', help_text="Bisa Konfirmasi Ke Bagian Pendaftaran, Contoh : 221321", unique=True, null=True)
    sex = models.CharField('Jenis Kelamin', max_length=1, choices=choices.SEX)
    religion = models.CharField('Agama', choices=choices.RELIGION, max_length=10)
    handpone = models.CharField('No. HP', null=True, max_length=15)
    city_born = models.CharField('Tempat Lahir', max_length=100, help_text="Contoh: Kabupaten Bandung")
    date_born = models.DateField('Tanggal Lahir', null=True)
    social_media = models.CharField('Akun Sosial Media', max_length=100, help_text="Seperti Alamat Twitter, IG, atau FB")
    achievement = models.TextField('Prestasi Akademik/Non Akademik', max_length=120, null=True, blank=True, help_text="Contoh : Juara 3 Lomba Basket Antar SMA Tingkat Kabupaten tahun 2018 atau Juara 3 Pencak Silat Ditingkat Kabupaten tahun 2018 ")

    # Documents Information
    nisn = models.PositiveIntegerField('NISN', unique=True, null=True, help_text="Isi berdasarkan NISN yang diberikan SMP Asal")
    nik = models.PositiveIntegerField('Nomor Induk Kependudukan (NIK)', unique=True, null=True, help_text="Bisa dicek di Kartu Keluarga")
    no_kk = models.PositiveIntegerField('Nomor Kartu Keluarga (KK)', null=True, help_text="Diisi Berdasarkan Kartu Keluarga")
    address_kk = models.TextField('Alamat Kartu Keluarga (KK)', null=True, help_text="Contoh: Jalan Radio Palasari")

    # Address
    city = models.CharField('Kota/Kabupaten', max_length=120, help_text="Contoh: Kabupaten Bandung")
    kecamatan = models.CharField(max_length=120, help_text="Contoh : Kecamatan Dayeuhkolot")
    kelurahan = models.CharField(max_length=120, help_text="Contoh : Desa Citeureup")
    dusun = models.CharField(max_length=120, help_text="Jika tidak tahu ada maka diisi dengan -")
    rt_rw = models.CharField('RT/RW', max_length=8, help_text="Contoh: 06/02")
    real_address = models.TextField('Alamat Sekarang', help_text="Contoh : Jalan Bojongsoang")
    resident = models.CharField('Tempat Tinggal', max_length=50, help_text="Contoh: Rumah Pribadi, Kost, Rumah Keluarga (Keluarga Besar).")
    transport = models.CharField('Alat Transportasi', max_length=50, help_text="Contoh: Jalan Kaki, Motor, Ojek Online, Sepeda, Mobil, Angkot.")

    # Previous School Information
    school_origin = models.CharField('Asal Sekolah', max_length=120, help_text="Isilah sesuai dengan asal sekolah Anda dan dituliskan seperti contoh berikut : SMP Telkom Bandung ")
    npsn_school_origin = models.PositiveIntegerField('Nomor NPSN Sekolah Asal', help_text="Bisa Cek <a href='https://referensi.data.kemdikbud.go.id/index11.php' target='_blank'><b>Disini</b></a>", null=True)

    # Medical Record
    medic_record = models.TextField('Riwayat Kesehatan', null=True, blank=True, help_text="Jika pernah mempunyai penyakit, silahkan ditulis disini")
    blood_type = models.CharField('Golongan Darah', choices=choices.BLOOD_TYPE, max_length=2)
    in_medicine = models.CharField('Dalam Pengobatan', max_length=120, null=True, blank=True)
    private_doctor = models.CharField('Nama Dokter Keluarga', max_length=120, null=True, blank=True, help_text="Jika kamu mempunyai dokter keluarga, silahkan input disini")
    phone_doctor = models.CharField('No Telepon Dokter', max_length=15, null=True, blank=True, help_text="Isi jika memiliki dokter keluarga dan atau dalam masa penyambuhan penyakit")

    def __str__(self):
        return f'{self.student} profile'

class ProfileParent(models.Model):
    """
    Creating abstract models, so this models (field) can be use multiple time (inheritance).
    https://docs.djangoproject.com/en/3.1/topics/db/models/#abstract-base-classes
    """
    verified = models.BooleanField(default=False, db_index=True)
    student = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    full_name = models.CharField(verbose_name=f"Nama Lengkap", max_length=120, db_index=True)
    city_born = models.CharField('Kota/Kabupaten Kelahiran', max_length=120, help_text="Contoh pengisian tempat lahir: Kab bandung")
    date_born = models.DateField('Tanggal Lahir', null=True)
    nik = models.PositiveIntegerField('Nomor Induk Kependudukan (NIK)', null=True, help_text="Diisi berdasarkan Kartu Keluarga")
    education = models.CharField(f'Pendidikan Terakhir', max_length=4, choices=choices.EDUCATION_LEVEL)
    job = models.CharField(f'Pekerjaan', max_length=100, null=True, blank=True)
    salary = models.PositiveIntegerField(f'Penghasilan', null=True, blank=True, help_text="Diisi dengan angka")
    email = models.EmailField(f'Email', null=True, blank=True)
    phone = models.CharField(f'No. HP', null=True, max_length=15)

    def __str__(self):
        return self.full_name

    class Meta:
        abstract = True

class FatherStudentProfile(ProfileParent):
    pass

class MotherStudentProfile(ProfileParent):
    pass

class StudentGuardianProfile(ProfileParent):
    pass

class MajorStudent(models.Model):
    student = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    verified = models.BooleanField(default=False, db_index=True)
    first_major = models.CharField('Pilihan Jurusan Pertama', choices=choices.MAJOR, max_length=4)
    second_major = models.CharField('Pilihan Jurusan Kedua', choices=choices.MAJOR, max_length=4)
    info = models.CharField('Info Primaseru (PPDB)', max_length=120, help_text="Tuliskan Darimana Kamu Mendapatkan Info Tentang Primaseru.")

    def __str__(self):
        return f'{self.student} - {self.first_major}'

class RegisterSchedule(models.Model):
    name = models.CharField('Nama Gelombang Pendaftaran', max_length=120)
    start_date = models.DateField('Tanggal Dimulai Pendaftaran')
    end_date = models.DateField('Tanggal Berakhir Pendaftaran')

    def __str__(self):
        return self.name

    @property
    def is_ongoing(self):
        return date.today().month <= self.end_date.month and date.today().month >= self.start_date.month

    @property
    def is_past_date(self):
        return date.today() > self.end_date

dashboard/forms.py
from django import forms
import datetime

from primaseru import models as prim_models
from primaseru import forms as prim_forms

from . import layouts
from .models import StudentStatus

from crispy_forms.helper import FormHelper


class AddRegisterNumberForm(forms.ModelForm):

    class Meta:
        model = prim_models.StudentProfile
        fields = ['no_regis']


class StudentStatusForm(forms.ModelForm):
    CONFIRM = [
        (None, '=Pilih='),
        (True, 'Diterima'),
        (False, 'Tidak Diterima'),
    ]
    accepted = forms.ChoiceField(choices=CONFIRM, label='Status')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
        self.form_tag = True
        self.helper.form_class = 'col-sm-12 my-3 p-3 verified-form'
        self.helper.form_id = 'status-form'
        self.helper.layout = layouts.DASHBOARD_STATUS

    class Meta:
        model = StudentStatus
        exclude = ['student']

class RegisterScheduleForm(forms.ModelForm):

    start_date = forms.DateField(label='Tanggal Mulai',initial=datetime.date.today, widget=forms.DateInput(format="%d/%m/%Y"),
                                help_text="Format: <em>DD/MM/YYYY</em>", input_formats=["%d/%m/%Y"])

    end_date = forms.DateField(label='Tanggal Berakhir',initial=datetime.date.today, widget=forms.DateInput(format="%d/%m/%Y"),
                                help_text="Format: <em>DD/MM/YYYY</em>", input_formats=["%d/%m/%Y"])

    class Meta:
        model = prim_models.RegisterSchedule
        fields = '__all__'

class DashboardStudentProfileForm(prim_forms.StudentProfileForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper.form_class = 'col-lg-12 col-md-12 my-3 p-3 verified-form'
        self.helper.form_id = 'siswa-form'
        self.helper.layout = layouts.DASHBOARD_STUDENT

    class Meta(prim_forms.StudentProfileForm.Meta):
        exclude = ['student']


class DashboardFilesForm(prim_forms.StudentFileForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper.form_class = 'col-lg-12 col-md-12 my-3 p-3 verified-form'
        self.helper.form_id = 'berkas-form'
        self.helper.label_class = None
        self.helper.field_class = None
        self.helper.layout = layouts.DASHBOARD_FILES

    class Meta(prim_forms.StudentFileForm.Meta):
        exclude = ['student', 'created_at', 'updated_at']


class DashboardMajorForm(prim_forms.MajorStudentForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper.form_class = 'col-lg-12 col-md-12 my-3 p-3 verified-form'
        self.helper.form_id = 'jurusan-form'
        self.helper.layout = layouts.DASHBOARD_MAJOR

    class Meta(prim_forms.MajorStudentForm.Meta):
        exclude = ['student']


class DashboardFatherForm(prim_forms.FatherStudentProfileForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper.form_class = 'col-lg-12 col-md-12 my-3 p-3 verified-form'
        self.helper.form_id = 'ayah-form'
        self.helper.layout = layouts.DASHBOARD_PARENT

    class Meta(prim_forms.FatherStudentProfileForm.Meta):
        exclude = ['student']


class DashboardMotherForm(DashboardFatherForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper.form_id = 'ibu-form'

    class Meta(DashboardFatherForm.Meta):
        model = prim_models.MotherStudentProfile

class DashboardGuardianForm(DashboardFatherForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper.form_id = 'wali-form'

    class Meta(DashboardFatherForm.Meta):
        model = prim_models.StudentGuardianProfile

dashboard/templates/dashboard/dashboard.html
{% extends 'dashboard/dashboard_base.html' %}
{% load crispy_forms_tags %}
{% block dashtitle %}
    Dashboard Primaseru <br />
    <a class="btn btn-light" data-toggle="modal" data-target="#registerModal" href="javascript:void(0)">Tambah Pendaftar</a>
{% endblock dashtitle %}
{% block head %}
    {{ block.super  }}
{% endblock head %}
{% block maindash %}
    <div class="row py-4">
        <div class="col-md m-2 p-3 bg-white rounded shadow">
            <h4 class="mb-1 judul">Total Pendaftar</h4>
            <br />
            <h3 class="mb-0 mt-1">{{ jumlah_siswa }} <small class="text-muted h6 judul">siswa</small></h3>
        </div>
        <div class="col-md m-2 p-3 bg-white rounded shadow">
            <h4 class="mb-1 judul">Total Pendaftar</h4><span class="badge badge-danger">BELUM TERVERIFIKASI</span>
            <br />
            <h3 class="mb-0 mt-1">{{ siswa_not_verified }} <small class="text-muted h6 judul">siswa</small></h3>
        </div>
        <div class="col-md m-2  p-3 bg-white rounded shadow">
            <h4 class="mb-1 judul">Total Pendaftar</h4><span class="badge badge-primary">TERVERIFIKASI</span>
            <br />
            <h3 class="mb-0 mt-1">{{ siswa_verified }} <small class="text-muted h6 judul">siswa</small></h3>
        </div>
        <div class="col-md m-2  p-3 bg-white rounded shadow">
            <h4 class="mb-1 judul">Total Pendaftar</h4><span class="badge badge-success">DITERIMA/LULUS</span>
            <br />
            <h3 class="mb-0 mt-1">{{ siswa_accepted }} <small class="text-muted h6 judul">siswa</small></h3>
        </div>
    </div>

    <div class="row px-2">
        <div class="col-md-12 py-2 bg-white rounded shadow">
            <div class="row">
                <div class="col">
                    <h3 class="judul">Daftar Calon Murid</h3>
                </div>
                <div class="col d-flex justify-content-end align-items-start">
                    <a class="btn btn-sm btn-outline-danger" href="{% url 'export-student' %}">Export</a>
                </div>
            </div>
            <div class="table-responsive-md">
                <table class="table table-hover table-sm">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col" class="w-25">Nama</th>
                            <th scope="col">Jenis Kelamin</th>
                            <th scope="col">Tempat Lahir</th>
                            <th scope="col">Tanggal Lahir</th>
                            <th scope="col">Status</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for s in siswa %}
                            <tr>
                                <th scope="row">{{ forloop.counter  }}</th>
                                <td><a href="{% url 'detail-student' s.student.pk %}">{{ s.student.full_name|title  }}</a></td>
                                <td>{{ s.get_sex_display  }}</td>
                                <td>{{ s.city_born  }}</td>
                                <td>{{ s.date_born|date:"d M Y"  }}</td>
                                <td>
                                    {% if s.student.studentstatus.accepted %}
                                        <span class="badge badge-success">DITERIMA</span>
                                    {% elif s.verified %}
                                        <span class="badge badge-primary">TERVERIFIKASI</span>
                                    {% else %}
                                        <span class="badge badge-danger">BELUM TERVERIFIKASI</span>
                                    {% endif %}
                                </td>
                                <td>
                                    <form method="POST" class="" action="{% url 'delete-student' s.student.pk %}">
                                        {% csrf_token %}
                                        <div class="dropdown">
                                            <button class="btn btn-danger dropdown-toggle btn-sm" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Action
                                            </button>
                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                <input type="submit" value="Delete" class="dropdown-item">
                                                <a class="dropdown-item" href="/admin/users/customuser/{{ s.student.pk }}/change/">Nama dan Email</a>
                                                <a class="dropdown-item" href="/admin/users/customuser/{{ s.student.pk }}/password/">Password</a>
                                            </div>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-12">
        <!-- PAGINATING -->
        {% if is_paginated %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center ">
                    {% if siswa.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                        <li class="page-item">
                            <a class="page-link" href="?page{{ siswa.previous_page_number }}">
                                <span aria-colspan="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="">First</a></li>
                        <li class="page-item disabled">
                            <a class="page-link" href="#">
                                <span aria-colspan="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    {% endif %}

                    {% for n in siswa.paginator.page_range %}
                        {% if siswa.number == n %}
                            <li class="page-item active">
                                <a class="page-link" href="?page={{ n }}">{{ n }}</a>
                            </li>
                        {% elif n > siswa.number|add:'-4' and n < siswa.number|add:'4' %}
                            <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if siswa.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ siswa.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                        <li class="page-item"><a class="page-link" href="?page={{ siswa.paginator.num_pages }}">Last</a></li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                        <li class="page-item disabled"><a class="page-link" href="#">Last</a></li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}

    </div>

    <!-- MODAL -->
    <div class="modal fade" id="registerModal" tabindex="-1" aria-labelledby="registerModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="registerModal">Tambah Calon Siswa Baru</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="POST" id="add-student">
                        {% csrf_token %}
                        {{ form_r|crispy  }}
                        {{ form_a|crispy  }}
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                    <button type="submit" class="btn btn-primary" form="add-student">Simpan</button>
                </div>
            </div>
        </div>
    </div>
{% endblock maindash %}
{% block js %}
    {{ block.super  }}
    <script type="text/javascript">
     let formError = {{ form_error  }};
     if(formError) {
         $('#registerModal').modal('show');
     }
    </script>

{% endblock js %}

dashboard/templates/dashboard/registerschedule_form.html
{% extends 'dashboard/dashboard_base.html' %}
{% load crispy_forms_tags %}
{% block head %}
    {{ block.super  }}
{% endblock head %}
{% block dashtitle %}
    Tambah Daftar Jadwal Pendaftaran
{% endblock dashtitle %}
{% block maindash %}
    <div class="row px-3">
        <div class="col-12 bg-white rounded p-3 mt-4 shadow">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy  }}
                <input type="submit" value="Submit" class="btn btn-outline-primary">
            </form>
        </div>
    </div>

{% endblock maindash %}

dashboard/templates/dashboard/student_change.html
{% load crispy_forms_tags %}

<form method="POST" action="" id="update-student">
    {% csrf_token %}
    {{ form|crispy  }}
</form>