exam/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.ExamView.as_view(), name="exam-list"),
    # Exam Path
    path('<int:pk>/', views.ExamViewDetail.as_view(), name="exam-detail"),
    path('<int:pk>/update/', views.ExamUpdateView.as_view(), name="exam-update"),
    path('<int:pk>/delete/', views.ExamDeleteView.as_view(), name="exam-delete"),
    path('<int:pk>/enroll/', views.ExamEnrollView.as_view(), name="exam-enroll"),
    path('<int:pk_exam>/timer/', views.ExamTimerView.as_view(), name="exam-timer"),
    path('<int:pk_exam>/times/up/', views.ExamTimesUpView.as_view(), name="exam-times-up"),
    # Question Path
    path('<int:pk>/question/add/', views.AddQuestion.as_view(), name="question-add"),
    path('<int:pk_exam>/taken/', views.TakeExamView.as_view(), name="taken-question"),
    path('<int:pk_exam>/taken/submit/', views.SubmitAnswer.as_view(), name="submit-question"),
    path('<int:pk_exam>/taken/<int:pk>/', views.RetriveAnswer.as_view(), name="question-answer"),
    path('<int:pk_exam>/question/<int:pk>/delete/', views.QuestionDeleteView.as_view(), name="question-delete"),
    path('<int:pk_exam>/question/<int:pk>/update/', views.QuestionUpdateView.as_view(), name="question-update"),
    path('answer/<int:pk>/', views.AnswerView.as_view(), name="answer-list"),
]

ppdb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from users.forms import CustomAuthenticationForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('primaseru.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('exam/', include('exam.urls')),

    path('login/', auth_views.LoginView.as_view(template_name='users/login.html',
                                                authentication_form=CustomAuthenticationForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

primaseru/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('profile/', views.studentProfile, name="profile"),
    path('profile/kartu-peserta/', views.render_register_card_view, name="profile-card"),
    path('profile/ayah/', views.ProfileView.as_view(), name="profile-ayah"),
    path('profile/ibu/', views.MoatherProfileView.as_view(), name="profile-ibu"),
    path('profile/siswa/', views.StudentProfileView.as_view(), name="profile-siswa"),
    path('profile/wali/', views.GuardianProfileView.as_view(), name="profile-wali"),
    path('profile/jurusan/', views.MajorStudentView.as_view(), name="jurusan-siswa"),
    path('profile/berkas/', views.FilesStudentView.as_view(), name="berkas-siswa"),
]

primaseru/models.py
from datetime import date

from django.db import models
from django.utils import timezone

from PIL import Image

from users.models import CustomUser
from . import choices


def user_directory_path(instance, filename):
    return f'berkas_{instance.student.id}_{instance.student.full_name}/{filename}'

class StudentFile(models.Model):
    student = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    verified = models.BooleanField(default=False, db_index=True)
    msg = models.CharField("Pesan", max_length=120, null=True, blank=True)
    ra_sem_1 = models.FileField('Rapor Semester 1', upload_to=user_directory_path, null=True, blank=True)
    ra_sem_2 = models.FileField('Rapor Semester 2', upload_to=user_directory_path, null=True, blank=True)
    ra_sem_3 = models.FileField('Rapor Semester 3', upload_to=user_directory_path, null=True, blank=True)
    ra_sem_4 = models.FileField('Rapor Semester 4', upload_to=user_directory_path, null=True, blank=True)
    ra_sem_5 = models.FileField('Rapor Semester 5', upload_to=user_directory_path, null=True, blank=True)
    color_blind_cert = models.FileField('Semester Keterangan Tidak Buta Warna', upload_to=user_directory_path, null=True, blank=True)
    healty_cert = models.FileField('Surat Keterangan Sehat', upload_to=user_directory_path, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'Raport {self.student}'

class PhotoProfile(models.Model):
    student = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    image = models.ImageField('Photo', default='default_photo.png', upload_to='profile_pics')

    def __str__(self):
        return f'Photo {self.student}'

    def save(self, *args, **kwargs):
        super(PhotoProfile, self).save(*args, **kwargs)
        img = Image.open(self.image.path)

        if img.height > 400 or img.width > 400:
            output_size = (400,400)
            img.thumbnail(output_size)
            img.save(self.image.path)


class StudentProfile(models.Model):
    verified = models.BooleanField(default=False, db_index=True)
    # Personal Information
    student = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    no_regis = models.PositiveIntegerField('No. Pendaftaran', help_text="Bisa Konfirmasi Ke Bagian Pendaftaran, Contoh : 221321", unique=True, null=True)
    sex = models.CharField('Jenis Kelamin', max_length=1, choices=choices.SEX)
    religion = models.CharField('Agama', choices=choices.RELIGION, max_length=10)
    handpone = models.CharField('No. HP', null=True, max_length=15)
    city_born = models.CharField('Tempat Lahir', max_length=100, help_text="Contoh: Kabupaten Bandung")
    date_born = models.DateField('Tanggal Lahir', null=True)
    social_media = models.CharField('Akun Sosial Media', max_length=100, help_text="Seperti Alamat Twitter, IG, atau FB")
    achievement = models.TextField('Prestasi Akademik/Non Akademik', max_length=120, null=True, blank=True, help_text="Contoh : Juara 3 Lomba Basket Antar SMA Tingkat Kabupaten tahun 2018 atau Juara 3 Pencak Silat Ditingkat Kabupaten tahun 2018 ")

    # Documents Information
    nisn = models.PositiveIntegerField('NISN', unique=True, null=True, help_text="Isi berdasarkan NISN yang diberikan SMP Asal")
    nik = models.PositiveIntegerField('Nomor Induk Kependudukan (NIK)', unique=True, null=True, help_text="Bisa dicek di Kartu Keluarga")
    no_kk = models.PositiveIntegerField('Nomor Kartu Keluarga (KK)', null=True, help_text="Diisi Berdasarkan Kartu Keluarga")
    address_kk = models.TextField('Alamat Kartu Keluarga (KK)', null=True, help_text="Contoh: Jalan Radio Palasari")

    # Address
    city = models.CharField('Kota/Kabupaten', max_length=120, help_text="Contoh: Kabupaten Bandung")
    kecamatan = models.CharField(max_length=120, help_text="Contoh : Kecamatan Dayeuhkolot")
    kelurahan = models.CharField(max_length=120, help_text="Contoh : Desa Citeureup")
    dusun = models.CharField(max_length=120, help_text="Jika tidak tahu ada maka diisi dengan -")
    rt_rw = models.CharField('RT/RW', max_length=8, help_text="Contoh: 06/02")
    real_address = models.TextField('Alamat Sekarang', help_text="Contoh : Jalan Bojongsoang")
    resident = models.CharField('Tempat Tinggal', max_length=50, help_text="Contoh: Rumah Pribadi, Kost, Rumah Keluarga (Keluarga Besar).")
    transport = models.CharField('Alat Transportasi', max_length=50, help_text="Contoh: Jalan Kaki, Motor, Ojek Online, Sepeda, Mobil, Angkot.")

    # Previous School Information
    school_origin = models.CharField('Asal Sekolah', max_length=120, help_text="Isilah sesuai dengan asal sekolah Anda dan dituliskan seperti contoh berikut : SMP Telkom Bandung ")
    npsn_school_origin = models.PositiveIntegerField('Nomor NPSN Sekolah Asal', help_text="Bisa Cek <a href='https://referensi.data.kemdikbud.go.id/index11.php' target='_blank'><b>Disini</b></a>", null=True)

    # Medical Record
    medic_record = models.TextField('Riwayat Kesehatan', null=True, blank=True, help_text="Jika pernah mempunyai penyakit, silahkan ditulis disini")
    blood_type = models.CharField('Golongan Darah', choices=choices.BLOOD_TYPE, max_length=2)
    in_medicine = models.CharField('Dalam Pengobatan', max_length=120, null=True, blank=True)
    private_doctor = models.CharField('Nama Dokter Keluarga', max_length=120, null=True, blank=True, help_text="Jika kamu mempunyai dokter keluarga, silahkan input disini")
    phone_doctor = models.CharField('No Telepon Dokter', max_length=15, null=True, blank=True, help_text="Isi jika memiliki dokter keluarga dan atau dalam masa penyambuhan penyakit")

    def __str__(self):
        return f'{self.student} profile'

class ProfileParent(models.Model):
    """
    Creating abstract models, so this models (field) can be use multiple time (inheritance).
    https://docs.djangoproject.com/en/3.1/topics/db/models/#abstract-base-classes
    """
    verified = models.BooleanField(default=False, db_index=True)
    student = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    full_name = models.CharField(verbose_name=f"Nama Lengkap", max_length=120, db_index=True)
    city_born = models.CharField('Kota/Kabupaten Kelahiran', max_length=120, help_text="Contoh pengisian tempat lahir: Kab bandung")
    date_born = models.DateField('Tanggal Lahir', null=True)
    nik = models.PositiveIntegerField('Nomor Induk Kependudukan (NIK)', null=True, help_text="Diisi berdasarkan Kartu Keluarga")
    education = models.CharField(f'Pendidikan Terakhir', max_length=4, choices=choices.EDUCATION_LEVEL)
    job = models.CharField(f'Pekerjaan', max_length=100, null=True, blank=True)
    salary = models.PositiveIntegerField(f'Penghasilan', null=True, blank=True, help_text="Diisi dengan angka")
    email = models.EmailField(f'Email', null=True, blank=True)
    phone = models.CharField(f'No. HP', null=True, max_length=15)

    def __str__(self):
        return self.full_name

    class Meta:
        abstract = True

class FatherStudentProfile(ProfileParent):
    pass

class MotherStudentProfile(ProfileParent):
    pass

class StudentGuardianProfile(ProfileParent):
    pass

class MajorStudent(models.Model):
    student = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    verified = models.BooleanField(default=False, db_index=True)
    first_major = models.CharField('Pilihan Jurusan Pertama', choices=choices.MAJOR, max_length=4)
    second_major = models.CharField('Pilihan Jurusan Kedua', choices=choices.MAJOR, max_length=4)
    info = models.CharField('Info Primaseru (PPDB)', max_length=120, help_text="Tuliskan Darimana Kamu Mendapatkan Info Tentang Primaseru.")

    def __str__(self):
        return f'{self.student} - {self.first_major}'

class RegisterSchedule(models.Model):
    name = models.CharField('Nama Gelombang Pendaftaran', max_length=120)
    start_date = models.DateField('Tanggal Dimulai Pendaftaran')
    end_date = models.DateField('Tanggal Berakhir Pendaftaran')

    def __str__(self):
        return self.name

    @property
    def is_ongoing(self):
        return date.today().month <= self.end_date.month and date.today().month >= self.start_date.month

    @property
    def is_past_date(self):
        return date.today() > self.end_date

primaseru/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.template.context_processors import csrf
from django.views import View
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.template.loader import get_template

from crispy_forms.utils import render_crispy_form
from xhtml2pdf import pisa

from . import forms, models
from .converter import link_callback_pdf
from dashboard.models import StudentStatus


def home(request):
    jadwal = models.RegisterSchedule.objects.all()

    return render(request, 'primaseru/timeline.html', {'jadwal': jadwal})

class ProfileView(LoginRequiredMixin, View):
    """
    Create base view for filling profile about student cadidate
    like: his/her father, mother, etc...
    father (Ayah) is the default here.
    """
    form_class = forms.FatherStudentProfileForm
    models = models.FatherStudentProfile
    template_name = 'primaseru/profile.html'
    name = "ayah"

    def get(self, request, *args, **kwargs):
        if not request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            raise PermissionDenied

        data = self.models.objects.get(student=request.user)
        form = self.form_class(instance=data)
        return render(request, self.template_name, {"form": form, "name": self.name, "data": data})

    def post(self, request, *args, **kwargs):
        data = self.models.objects.get(student=request.user)
        if data.verified:
            return JsonResponse({'success': False}, status=409)

        form = self.form_class(request.POST, request.FILES or None, instance=data)
        ctx = {}
        ctx.update(csrf(request))

        if form.is_valid():
            form.save()
            form = render_crispy_form(form, context=ctx)
            return JsonResponse({'success': True, 'form_s': form}, status=200)

        form = render_crispy_form(form, context=ctx)
        return JsonResponse({'success': False, 'form_s': form}, status=406)

class StudentProfileView(ProfileView):
    form_class = forms.StudentProfileForm
    models = models.StudentProfile
    name = "siswa"

class MoatherProfileView(ProfileView):
    form_class = forms.MotherStudentProfileForm
    models = models.MotherStudentProfile
    name = "ibu"

class GuardianProfileView(ProfileView):
    form_class = forms.StudentGuardianProfileForm
    models = models.StudentGuardianProfile
    name = "wali"

class MajorStudentView(ProfileView):
    form_class = forms.MajorStudentForm
    models = models.MajorStudent
    template_name = "primaseru/major.html"
    name = "jurusan"

class FilesStudentView(ProfileView):
    form_class = forms.StudentFileForm
    models = models.StudentFile
    template_name = "primaseru/student_files.html"
    name = "berkas"

def render_register_card_view(request):
    template_path = 'primaseru/register_card.html'
    profile = models.StudentProfile.objects.get(student=request.user)
    major = models.MajorStudent.objects.get(student=request.user)

    context = {
        'profile': profile,
        'major': major,
    }

    response = HttpResponse(content_type="application/pdf")
    response['Content-Disposition'] = f'attachment; filename="Kartu Peserta_{request.user.full_name}.pdf"'

    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
        html, dest=response, link_callback=link_callback_pdf)

    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')

    return response


@login_required
def studentProfile(request):
    if request.user.is_staff:
        return redirect('dashboard')

    if request.method == "POST":
        form_ph = forms.PhotoProfileForm(request.POST, request.FILES, instance=request.user.photoprofile)
        if form_ph.is_valid():
            form_ph.save()
            return redirect('profile')
    else:
        ctx = {
               'form_ph': forms.PhotoProfileForm(instance=request.user.photoprofile),
               'profile': models.PhotoProfile.objects.get(student=request.user),
               'status': StudentStatus.objects.get(student=request.user),
           }
        return render(request, 'primaseru/primaseru.html', context=ctx)

primaseru/templates/primaseru/major.html
{% load crispy_forms_tags %}
<div class="card card-bg mx-3 mb-3 w-100">
    <div class="card-body">
        <h5 class="card-title">Pemilihan {{ name|capfirst  }}</h5>
        <p class="card-text">
            Silahkan memilih {{ name|capfirst }} Anda sesuai minat, jika terdapat tanda bintang (<span class="text-danger">*</span>) berarti wajib diisi.
            <samp class="text-danger">Jurusan yang sudah dipilih tidak bisa diubah.</samp>
        </p>
    </div>
</div>
{% crispy form %}
{% if data.verified %}
    <script type="text/javascript">
    $("#{{ name }}-form .form-control").prop('disabled', true);
    $("#{{ name }}-form").submit(() => {
        let alertSuccess = `<div class="alert alert-warning alert-dismissible fade show" role="alert">Data yang sudah diverifikasi, tidak bisa diubah \
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">\
        &times;</span></button></div>`;
        $("#{{ name }}-form").prepend(alertSuccess);
        return false;
    });
    </script>
{% else %}
<script type="text/javascript">
let selectedFirst = $("#id_first_major").val();
let selectedSecond = $("#id_second_major").val();
let disableMajor = () => {
    let selectedFirst = $("#id_first_major").val();
    let selectedSecond = $("#id_second_major").val();
    if (!!(selectedFirst)) {
        $("#id_first_major").prop('disabled', true);
    }
    if (!!(selectedSecond)) {
        $("#id_second_major").prop('disabled', true);
    }
}
disableMajor();

    $("#{{ name }}-form").submit((e) => {
        if ($("#id_first_major").is(":disabled") && $("#id_second_major").is(":disabled") || (!!(selectedFirst) || !!(selectedSecond))) {
            let alertDanger = `<div class="alert alert-danger alert-dismissible fade show" role="alert">Jurusan Sudah Dipilih, Tidak Bisa Diubah.... \
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">\
                                    &times;</span></button></div>`;
            $("#{{ name }}-form").prepend(alertDanger);
            e.preventDefault();
            e.stopPropagation();
        } else {
            $.ajax({
                url: "/profile/jurusan/",
                type: "POST",
                data: $("#{{ name }}-form").serialize(),
                dataType: 'json',
                beforeSend: () => {
                    let alertDanger = `<div class="alert alert-danger alert-dismissible fade show" role="alert">Kedua juruan pilihan tidak boleh sama! \
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">\
                                    &times;</span></button></div>`;
                    if ($("#id_first_major").val() == $("#id_second_major").val()) {
                        $("#{{ name }}-form").prepend(alertDanger);
                        return false;
                    }
                    $("#{{ name }}-form").empty().html(`<div class="d-flex justify-content-center" >
                        <div class="spinner-border text-danger" role="status" style="width: 3rem; height: 3rem;">
                            <span class="sr-only">Loading...</span>
                        </div>
                        </div>`
                    );
                },
                success: (response) => {
                    $("#{{ name }}-form").empty().html(response.form_s);
                    let alertSuccess = `<div class="alert alert-success alert-dismissible fade show" role="alert">Berhasil Menyimpan Jurusan Pilihan \
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">\
                                    &times;</span></button></div>`;
                    disableMajor()
                    $("#{{ name }}-form").prepend(alertSuccess);
                },
                error: (response) => {
                    $("#{{ name }}-form").empty().html(response.form_s);
                    let alertDanger = `<div class="alert alert-danger alert-dismissible fade show" role="alert">Data Tidak Valid, Silahkan Cek Kembali... \
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">\
                                    &times;</span></button></div>`;
                    $("#{{ name }}-form").prepend(alertDanger);
                },
            });
            return false;
        }
    });

</script>
{% endif %}

primaseru/templates/primaseru/primaseru.html
{% extends 'users/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
    <style type="text/css" media="screen">
     .min-vh{
         min-height: 50vh;
     }
     .banner {
         border-radius: 0.25rem;
         color: #fff;
         background-color: #FF0000;
     }
     .nav .nav-link:hover::after {
         width: 100%;
     }
     #v-pills-tab .nav-link:hover {
         border-bottom: 2px solid #aaa;
     }
     #v-pills-tab .nav-link.active{
         color: red;
         border-bottom: 2px solid red;
     }
     .card-bg {
         background-color: #fff2f4;
         border-color: #ffc9c6;
     }
    </style>
{% endblock head %}
{% block navbar %}{% endblock navbar %}
{% block container %}container-fluid{% endblock container %}
{% block main %}


    <div class="row py-2 pt-4">
        <div class="col-sm-3 text-center mb-1">
            <img src="{{ profile.image.url }}" alt="photo profile" width="175" height="175" />
        </div>
        <div class="col-sm-9 mb-1">
            <h1>{{ profile.student.full_name|title  }} </h1>
            <h4 class="text-muted">{{ profile.student.email  }}</h4>
            <form method="POST" enctype="multipart/form-data" id="photo-profile-form" name="photo-profile-form">
                {% csrf_token %}
                <div class="custom-file">
                    <input type="file" accept="image/*" class="custom-file-input" value="{{ form_ph.image.value }}" id="{{ form_ph.image.auto_id }}" name="{{ form_ph.image.name }}">
                    <label class="custom-file-label" for="{{ form_ph.image.auto_id }}">Upload Photo</label>
                </div>
            </form>
            {% if status.accepted %}
                <div class="alert alert-success mt-3 mb-0" role="alert">
                    Selamat Anda Dinyatakan Diterima di SMK Telkom Bandung! <br />
                    Jurusan: {{ status.get_major_display  }}
                </div>
            {% elif status.accepted == False %}
                <div class="alert alert-danger mt-3 mb-0" role="alert">
                    Jangan bersedih hati, Anda belum diterima di SMK Telkom Bandung.
                </div>
            {% endif %}
            <a class="btn btn-outline-secondary btn-sm mt-3" href="{% url 'logout' %}">Logout</a>
            <a class="btn btn-info btn-sm mt-3" href="{% url 'profile-card' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cloud-arrow-down-fill" viewBox="0 0 16 16">
                    <path d="M8 2a5.53 5.53 0 0 0-3.594 1.342c-.766.66-1.321 1.52-1.464 2.383C1.266 6.095 0 7.555 0 9.318 0 11.366 1.708 13 3.781 13h8.906C14.502 13 16 11.57 16 9.773c0-1.636-1.242-2.969-2.834-3.194C12.923 3.999 10.69 2 8 2zm2.354 6.854l-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 1 1 .708-.708L7.5 9.293V5.5a.5.5 0 0 1 1 0v3.793l1.146-1.147a.5.5 0 0 1 .708.708z"/>
                </svg>
                Kartu Peserta
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-12 px-2 px-lg-5 bg-light border-bottom border-top">
            <div class="nav mx-0 mx-lg-5 px-0 px-lg-3" id="v-pills-tab" role="navigation">
                <a class="nav-link tab-profile active" id="v-pills-identity-tab" data-toggle="pill" href="#v-pills-identity" role="tab" aria-controls="v-pills-identity" aria-selected="true">Identitas Diri</a>
                <a class="nav-link tab-profile" id="v-pills-id-ayah-tab" data-toggle="pill" href="#v-pills-id-ayah" role="tab" aria-controls="v-pills-id-ayah" aria-selected="false">Identitas Ayah</a>
                <a class="nav-link tab-profile" id="v-pills-id-ibu-tab" data-toggle="pill" href="#v-pills-id-ibu" role="tab" aria-controls="v-pills-id-ibu" aria-selected="false">Identitas Ibu</a>
                <a class="nav-link tab-profile" id="v-pills-id-wali-tab" data-toggle="pill" href="#v-pills-id-wali" role="tab" aria-controls="v-pills-id-wali" aria-selected="false">Identitas Wali</a>
                <a class="nav-link tab-profile" id="v-pills-major-tab" data-toggle="pill" href="#v-pills-major" role="tab" aria-controls="v-pills-major" aria-selected="false">Jurusan</a>
                <a class="nav-link tab-profile" id="v-pills-files-tab" data-toggle="pill" href="#v-pills-files" role="tab" aria-controls="v-pills-files" aria-selected="false">Berkas</a>
                <a class="nav-link tab-profile" id="v-pills-exam-tab" data-toggle="pill" href="#v-pills-exam" role="tab" aria-controls="v-pills-exam" aria-selected="false">Ujian</a>
            </div>
        </div>
    </div>

    <div class="row bg-light pt-3">
        <div class="container">
            <div class="col-sm-12">
                <div class="tab-content" id="v-pills-tabContent">
                    <div class="tab-pane fade show active" id="v-pills-identity" role="tabpanel" aria-labelledby="v-pills-identity-tab">
                        <div class="row  rounded py-2 bg-white min-vh border mb-4" id="student-content">
                        </div>
                    </div>
                    <div class="tab-pane fade" id="v-pills-id-ayah" role="tabpanel" aria-labelledby="v-pills-id-ayah-tab">
                        <div class="row rounded py-2 bg-white min-vh border mb-4" id="father-content">
                        </div>
                    </div>
                    <div class="tab-pane fade" id="v-pills-id-ibu" role="tabpanel" aria-labelledby="v-pills-id-ibu-tab">
                        <div class="row  rounded py-2 bg-white min-vh border mb-4" id="mother-content">
                        </div>
                    </div>
                    <div class="tab-pane fade" id="v-pills-id-wali" role="tabpanel" aria-labelledby="v-pills-id-wali-tab">
                        <div class="row  rounded py-2 bg-white min-vh border mb-4" id="guardian-content">
                        </div>
                    </div>
                    <div class="tab-pane fade" id="v-pills-major" role="tabpanel" aria-labelledby="v-pills-major-tab">
                        <div class="row  rounded py-2 bg-white min-vh border mb-4" id="major-content">
                        </div>
                    </div>
                    <div class="tab-pane fade" id="v-pills-files" role="tabpanel" aria-labelledby="v-pills-files-tab">
                        <div class="row  rounded py-2 bg-white min-vh border mb-4" id="files-content">
                        </div>
                    </div>
                    <div class="tab-pane fade" id="v-pills-exam" role="tabpanel" aria-labelledby="v-pills-exam-tab">
                        <div class="row  rounded py-2 bg-white min-vh border mb-4">
                            <div class="col-12" id="exam-content">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock main %}
{% block js %}
    <script type="text/javascript" src="{% static 'primaseru/js/jquery-auto-resize.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'primaseru/js/getFormPrimaseru.js' %}"></script>
    <script type="text/javascript" src="{% static 'primaseru/js/primaseru.js' %}"></script>
{% endblock js %}